name: OKJRTRESCUE
favicon: null
layout_spectrum: 0.09979138220660388
typography_spectrum: 0.42752330703660846
title: Oklahoma Jack Russell Rescue - OJRR
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.11453217687085271
  lightness: 0.692217979580164
  saturation: 0.8759962732437998
  rhythmicContrast: 0.1915482950862497
purpose: []
